[package]
name = "jni-bridge"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "seekercore"
crate-type = ["cdylib"]

[dependencies]
engine.workspace = true
jni.workspace = true
log.workspace = true
serde_json.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
android_logger.workspace = true
