package to.eyed.thragg.solana.chain

import to.eyed.thragg.solana.build.BuildTasks
import to.eyed.thragg.solana.build.ProgramTarget
import to.eyed.thragg.solana.build.ProjectFramework
import to.eyed.thragg.solana.build.ProjectLayout
import to.eyed.thragg.solana.templates.SolanaProgram
import java.io.File

/**
 * Which program id a project *has*, given that three files each claim one.
 *
 * A Solana program's id is the public key of `target/deploy/<module>-keypair.json`
 * — that is what gets deployed under. But the source also hard-codes it in
 * `declare_id!("…")` (the program checks it at runtime and refuses to serve
 * under any other address), and an Anchor workspace repeats it a third time
 * in `[programs.<cluster>]`. On a laptop `anchor keys sync` keeps the three
 * in step. On this phone the keypair is generated by the first build — or by
 * [ensureKeypair] the moment a deploy needs it — and a cloned project arrives
 * with a `declare_id!` from someone else's laptop and no keypair at all. So
 * the three disagree routinely, and a deploy that silently picked one would
 * ship a program that rejects its own address.
 *
 * The order is keypair, then `declare_id!`, then Anchor.toml, because that is
 * the order of *authority*: the keypair is what actually signs the deploy,
 * `declare_id!` is what the deployed code will insist on, and Anchor.toml is
 * a copy of whichever of those last won. [Resolved.disagree] is the fact the
 * Deploy sheet turns into a notice, and [disagree] is the same fact in the
 * shape `BuildRunner.idsDisagree` wants.
 *
 * Everything here is plain file IO on the host filesystem — no Context — so
 * the whole reconciliation is exercised on the host against temp dirs.
 */
object ProgramIds {

    /**
     * The notice the Deploy sheet shows and the reason the deployer refuses:
     * a program whose `declare_id!` is not the keypair's address rejects
     * every instruction with DeclaredProgramIdMismatch, so deploying it
     * spends the rent on a program that cannot be called.
     */
    const val DISAGREE = "declare_id! does not match the program keypair — rebuild syncs them"

    /** Where the id in [Resolved.id] came from. */
    enum class Source { Keypair, DeclareId, AnchorToml, None }

    /**
     * The three claims side by side, and the one that wins.
     *
     * [disagree] is true only when two *present* claims differ: a project with
     * only a `declare_id!` is not in disagreement with the keypair it does not
     * have yet, and a Native project with no Anchor.toml never disagrees with
     * a table that does not exist.
     */
    data class Resolved(
        val id: String?,
        val source: Source,
        val keypairId: String?,
        val declaredId: String?,
        val anchorTomlId: String?,
    ) {
        val disagree: Boolean
            get() = listOfNotNull(keypairId, declaredId, anchorTomlId).distinct().size > 1
    }

    /**
     * The id [program] deploys under on [cluster], and what the other two
     * sources say. Blocking file reads; call it off the main thread.
     */
    fun resolve(projectRoot: String, program: ProgramTarget, cluster: Cluster): Resolved {
        val keypairId = Keypair.read(keypairFile(projectRoot, program))?.publicKey?.base58
        val declared = libRsFile(projectRoot, program)
            ?.let { runCatching { it.readText() }.getOrNull() }
            ?.let { declaredId(it) }
        val anchorToml = File(projectRoot, "Anchor.toml")
        val tomlId = if (anchorToml.isFile) {
            val text = runCatching { anchorToml.readText() }.getOrNull()
            text?.let {
                AnchorToml.programId(it, cluster.anchorName, program.moduleName)
                    ?: AnchorToml.programId(it, cluster.anchorName, program.crateName)
            }
        } else {
            null
        }
        val (id, source) = when {
            keypairId != null -> keypairId to Source.Keypair
            declared != null -> declared to Source.DeclareId
            tomlId != null -> tomlId to Source.AnchorToml
            else -> null to Source.None
        }
        return Resolved(id, source, keypairId, declared, tomlId)
    }

    /**
     * The address inside the first `declare_id!("…")` of a lib.rs, or null.
     *
     * A regex rather than a Rust parser: the macro takes one string literal
     * and nothing else, whitespace around the parentheses is the only
     * variation seen in the wild, and the address is validated as Base58 of
     * the right length so a commented-out placeholder like `declare_id!("...")`
     * is not mistaken for an id.
     */
    fun declaredId(libRsText: String): String? {
        val match = DECLARE_ID.find(libRsText) ?: return null
        val id = match.groupValues[1]
        return id.takeIf { Base58.isPubkey(it) }
    }

    /** `<root>/target/deploy/<module>-keypair.json` — where every build puts it. */
    fun keypairFile(projectRoot: String, program: ProgramTarget): File =
        File(projectRoot, "target/deploy/${program.moduleName}-keypair.json")

    /**
     * `<root>/programs_py/<module>.py` — a Seahorse program's source, and the
     * `declare_id('…')` the generated `lib.rs` copies its address from.
     */
    fun seahorseSourceFile(projectRoot: String, program: ProgramTarget): File =
        File(projectRoot, "programs_py/${program.moduleName}.py")

    /**
     * [text] with its first `declare_id('…')` naming [id], or null when there
     * is no `declare_id` to change or it already does. Seahorse accepts either
     * quote; whichever the file used is kept.
     */
    fun withSeahorseDeclaredId(text: String, id: String): String? {
        val match = SEAHORSE_DECLARE_ID.find(text) ?: return null
        if (match.groupValues[2] == id) return null
        val quote = match.groupValues[1]
        return text.replaceRange(match.range, "declare_id($quote$id$quote)")
    }

    /**
     * A `lib.rs` with its first `declare_id!("…")` naming [id], or null when
     * there is none to change or it already does — what `anchor keys sync`
     * writes, done here so it can happen before a keypair exists on disk
     * (see [syncProgramIds]). Only the address moves; the rest of the line
     * is the file's.
     */
    fun withDeclaredId(libRsText: String, id: String): String? {
        val match = DECLARE_ID.find(libRsText) ?: return null
        val group = match.groups[1] ?: return null
        if (group.value == id) return null
        return libRsText.replaceRange(group.range, id)
    }

    /**
     * Make every program's keypair when there is none, and point its other
     * claims — `declare_id!` in `lib.rs`, the Anchor.toml table, a Seahorse
     * program's Python — at that keypair's address, saying which files
     * changed (project-relative, the keypair's path among them). Blocking.
     * Every framework: an Anchor project has all three claims, a Seahorse one
     * has the Python too, and a Native one has only `src/lib.rs` — which is
     * still one claim too many to leave lying (see below).
     *
     * `anchor keys sync` fixes `declare_id!` in `lib.rs`, and the build that
     * runs after it is what the id is for. But two files it does not reach
     * on this phone:
     *
     *  - **Anchor.toml.** Measured on the Seeker 2026-09-08, after `keys
     *    sync` on a Seahorse project whose `[provider] cluster` was devnet:
     *    `lib.rs` and the Python carried the keypair's address, and
     *    Anchor.toml still read `[programs.localnet] sea_counter = "<the
     *    placeholder>"` with no `[programs.devnet]` table at all. Anchor's
     *    sync rewrites the table for the cluster the *provider* names only
     *    when that table exists, and the template writes `localnet` alone
     *    (SolanaTemplates.anchorToml). So the file lied about the id it
     *    deploys under, and [resolve] read it as a third, disagreeing claim.
     *    This writes `[programs.<provider cluster>]` when its row is missing
     *    or differs from the keypair, and fixes `[programs.localnet]` when
     *    it still holds [SolanaProgram.PLACEHOLDER_ID] — that table is
     *    Anchor's own convention and stays, but a placeholder in it is
     *    exactly what `keys sync` was meant to replace.
     *  - **The Python.** A Seahorse `lib.rs` is *generated* from
     *    `programs_py/<module>.py` on every build, so a sync that stops at
     *    `lib.rs` is undone by the build that follows it, and the program
     *    ships with the placeholder id again: DeclaredProgramIdMismatch on
     *    the first call. The Python is the source; [withSeahorseDeclaredId]
     *    is the sync for it.
     *
     *  - **A Native program's `declare_id!`, when it has one.** Playground's
     *    Native starter has none — a native program is not compiled against
     *    its own address — and neither does the scaffold here, so a fresh
     *    Native project has one claim (the keypair) and cannot disagree with
     *    itself. But a *cloned* native program, or one written by hand or by
     *    an older Thragg, does carry `declare_id!("…")`, and the keypair the
     *    first build generates for it is a different address. That is a real
     *    disagreement ([Resolved.disagree] is framework-agnostic, and so is
     *    the Deploy sheet's refusal), and until 2026-09-09 it was one nothing
     *    could resolve: the sheet said "rebuild syncs them" and the build
     *    returned `emptyList()` for Native, so the program could never be
     *    deployed (QA B-05). It is the same one-line rewrite Anchor gets,
     *    minus the two files a Native project does not have — Anchor.toml is
     *    absent, so the table half writes nothing, and the Python half is
     *    Seahorse's alone.
     *
     *  - **The keypair itself, and `lib.rs`, before the first build.** Until
     *    2026-09-08 a program with no keypair was left alone — "the first
     *    build makes one" — and that was the bug: a fresh Seahorse scaffold's
     *    first Build on the Seeker (tidepool, 2026-09-08) had `anchor build`
     *    generate the keypair and then refuse its own output with "Program
     *    ID mismatch detected … Please run `anchor keys sync`", because
     *    `seahorse build` had just regenerated `lib.rs` from a Python that
     *    still held the placeholder, and nothing could have synced it
     *    earlier with no keypair to sync to. The `.so` was still written,
     *    carrying the placeholder, and a deploy of it would have failed on
     *    its first instruction. So this generates the keypair when there is
     *    none ([ensureKeypair] — the same file `anchor build` would have
     *    made a minute later, so the state after the build is unchanged;
     *    only the order is) and writes `declare_id!` in `lib.rs` too
     *    ([withDeclaredId]), which is `anchor keys sync` done early; the
     *    real `keys sync` that follows in BuildRunner then finds nothing to
     *    do, and a fresh project's first build is right the first time.
     *
     * Idempotent: a file that already agrees is neither written nor
     * returned, and Anchor.toml is written at most once for all programs.
     */
    fun syncProgramIds(layout: ProjectLayout): List<String> {
        when (layout.framework) {
            ProjectFramework.Anchor, ProjectFramework.Seahorse, ProjectFramework.Native -> Unit
            ProjectFramework.Unknown -> return emptyList()
        }
        val changed = ArrayList<String>()
        val anchorToml = File(layout.root, "Anchor.toml")
        val originalToml = if (anchorToml.isFile) runCatching { anchorToml.readText() }.getOrNull() else null
        val cluster = originalToml
            ?.let { AnchorToml.providerCluster(it) }
            ?.let { Cluster.fromAnchor(it) }
            ?: Cluster.DEFAULT
        var toml = originalToml
        val rootDir = File(layout.root)
        for (program in layout.programs) {
            val keypairFile = keypairFile(layout.root, program)
            val keypairId = Keypair.read(keypairFile)?.publicKey?.base58
                ?: ensureKeypair(layout.root, program).publicKey.base58.also {
                    changed.add(keypairFile.relativeTo(rootDir).path)
                }
            libRsFile(layout.root, program)?.let { lib ->
                val text = runCatching { lib.readText() }.getOrNull() ?: return@let
                val rewritten = withDeclaredId(text, keypairId) ?: return@let
                lib.writeText(rewritten)
                changed.add(lib.relativeTo(rootDir).path)
            }
            toml = toml?.let { withAnchorTomlId(it, cluster, program.moduleName, keypairId, program.crateName) }
            if (layout.framework != ProjectFramework.Seahorse) continue
            val source = seahorseSourceFile(layout.root, program)
            val text = runCatching { source.readText() }.getOrNull() ?: continue
            val rewritten = withSeahorseDeclaredId(text, keypairId) ?: continue
            source.writeText(rewritten)
            changed.add("programs_py/${program.moduleName}.py")
        }
        if (toml != null && toml != originalToml) {
            anchorToml.writeText(toml)
            changed.add(0, "Anchor.toml")
        }
        return changed
    }

    /**
     * [text] with `[programs.<cluster>] module = "id"` — written when the row
     * is absent or names something else — and `[programs.localnet]`'s row for
     * [module] replaced when it still holds the scaffold's placeholder. The
     * same text back when both already hold, so a caller can compare to know
     * whether to write. Pure; the file-shaped half is [syncProgramIds].
     *
     * The row is keyed the way the file already keys it. The scaffold writes
     * the module name, but [resolve] also accepts a row under [crate] (a
     * hand-written or cloned Anchor.toml with `my-program = "…"`), and a sync
     * that only knew the module would *add* a second row under it and leave
     * the crate-keyed one holding the wrong id — a file that half lies.
     */
    fun withAnchorTomlId(text: String, cluster: Cluster, module: String, id: String, crate: String? = null): String {
        var out = text
        val key = keyFor(out, cluster.anchorName, module, crate)
        if (AnchorToml.programId(out, cluster.anchorName, key) != id) {
            out = AnchorToml.withProgramId(out, cluster.anchorName, key, id)
        }
        val localKey = keyFor(out, LOCALNET, module, crate)
        if (AnchorToml.programId(out, LOCALNET, localKey) == SolanaProgram.PLACEHOLDER_ID) {
            out = AnchorToml.withProgramId(out, LOCALNET, localKey, id)
        }
        return out
    }

    /** The key `[programs.<cluster>]` already uses for this program; the module name when neither is there. */
    private fun keyFor(text: String, cluster: String, module: String, crate: String?): String = when {
        AnchorToml.programId(text, cluster, module) != null -> module
        crate != null && AnchorToml.programId(text, cluster, crate) != null -> crate
        else -> module
    }

    /**
     * The program keypair, generated and written if there is none yet.
     * Blocking; call it off the main thread.
     *
     * Generating here rather than failing is what lets a cloned project — or
     * a Native build through platform-tools' cargo, which writes no keypair —
     * deploy at all. The id it gets is fresh, which is exactly the case
     * [Resolved.disagree] exists to point out.
     */
    fun ensureKeypair(projectRoot: String, program: ProgramTarget): Keypair {
        val file = keypairFile(projectRoot, program)
        Keypair.read(file)?.let { return it }
        val fresh = Keypair.generate()
        Keypair.write(file, fresh)
        return fresh
    }

    /**
     * Whether any program in [layout] has two present sources that disagree —
     * the shape `BuildRunner.idsDisagree` wants. Every framework but
     * [ProjectFramework.Unknown], including Native: a Native project has no
     * `anchor keys sync`, but it does have [syncProgramIds], which the build
     * runs before it compiles, so a mismatch there is a thing the build fixes
     * and saying so is honest. Answering `false` for Native was the other
     * half of QA B-05 — the deploy went ahead with a `declare_id!` the
     * program keypair did not match, which is a program that rejects every
     * instruction.
     *
     * The cluster is the one Anchor.toml names, falling back to
     * [Cluster.DEFAULT]; there is no Context here to ask [ClusterStore].
     */
    fun disagree(layout: ProjectLayout): Boolean {
        when (layout.framework) {
            ProjectFramework.Anchor, ProjectFramework.Seahorse, ProjectFramework.Native -> Unit
            ProjectFramework.Unknown -> return false
        }
        val anchorToml = File(layout.root, "Anchor.toml")
        val cluster = runCatching { anchorToml.readText() }.getOrNull()
            ?.let { AnchorToml.providerCluster(it) }
            ?.let { Cluster.fromAnchor(it) }
            ?: Cluster.DEFAULT
        return layout.programs.any { resolve(layout.root, it, cluster).disagree }
    }

    /**
     * The `lib.rs` that would carry [program]'s `declare_id!`, or null.
     *
     * Anchor keeps each program under `programs/<dir>/src/lib.rs`, and `<dir>`
     * is *usually* the crate name — but it is the directory's Cargo.toml that
     * decides, so a workspace whose folder is named differently is found by
     * reading those. Native is `src/lib.rs` at the root.
     */
    fun libRsFile(projectRoot: String, program: ProgramTarget): File? {
        val root = File(projectRoot)
        val programs = File(root, "programs")
        if (programs.isDirectory) {
            for (name in listOf(program.crateName, program.moduleName)) {
                val direct = File(programs, "$name/src/lib.rs")
                if (direct.isFile) return direct
            }
            for (dir in programs.listFiles().orEmpty()) {
                if (!dir.isDirectory) continue
                val manifest = File(dir, "Cargo.toml")
                if (!manifest.isFile) continue
                val parsed = runCatching { BuildTasks.parseManifest(manifest.readText()) }.getOrNull()
                    ?: continue
                if (parsed.packageName == program.crateName) {
                    val lib = File(dir, "src/lib.rs")
                    if (lib.isFile) return lib
                }
            }
        }
        val native = File(root, "src/lib.rs")
        return native.takeIf { it.isFile }
    }

    /**
     * The table the template writes and Anchor's `keys sync` expects to find:
     * not a [Cluster] (there is no validator on this phone), just the name.
     */
    private const val LOCALNET = "localnet"

    private val DECLARE_ID = Regex("""declare_id!\s*\(\s*"([1-9A-HJ-NP-Za-km-z]{32,44})"\s*\)""")

    /** Seahorse's `declare_id('…')`: a Python call, either quote, no `!`. */
    private val SEAHORSE_DECLARE_ID =
        Regex("""declare_id\s*\(\s*(['"])([1-9A-HJ-NP-Za-km-z]{32,44})\1\s*\)""")
}
