package to.eyed.seeker.code.solana.chain

import to.eyed.seeker.code.solana.build.BuildTasks
import to.eyed.seeker.code.solana.build.ProgramTarget
import to.eyed.seeker.code.solana.build.ProjectFramework
import to.eyed.seeker.code.solana.build.ProjectLayout
import java.io.File

/**
 * Which program id a project *has*, given that three files each claim one.
 *
 * A Solana program's id is the public key of `target/deploy/<module>-keypair.json`
 * — that is what gets deployed under. But the source also hard-codes it in
 * `declare_id!("…")` (the program checks it at runtime and refuses to serve
 * under any other address), and an Anchor workspace repeats it a third time
 * in `[programs.<cluster>]`. On a laptop `anchor keys sync` keeps the three
 * in step. On this phone the keypair is generated by the first build — or by
 * [ensureKeypair] the moment a deploy needs it — and a cloned project arrives
 * with a `declare_id!` from someone else's laptop and no keypair at all. So
 * the three disagree routinely, and a deploy that silently picked one would
 * ship a program that rejects its own address.
 *
 * The order is keypair, then `declare_id!`, then Anchor.toml, because that is
 * the order of *authority*: the keypair is what actually signs the deploy,
 * `declare_id!` is what the deployed code will insist on, and Anchor.toml is
 * a copy of whichever of those last won. [Resolved.disagree] is the fact the
 * Deploy sheet turns into a notice, and [disagree] is the same fact in the
 * shape `BuildRunner.idsDisagree` wants.
 *
 * Everything here is plain file IO on the host filesystem — no Context — so
 * the whole reconciliation is exercised on the host against temp dirs.
 */
object ProgramIds {

    /**
     * The notice the Deploy sheet shows and the reason the deployer refuses:
     * a program whose `declare_id!` is not the keypair's address rejects
     * every instruction with DeclaredProgramIdMismatch, so deploying it
     * spends the rent on a program that cannot be called.
     */
    const val DISAGREE = "declare_id! does not match the program keypair — rebuild syncs them"

    /** Where the id in [Resolved.id] came from. */
    enum class Source { Keypair, DeclareId, AnchorToml, None }

    /**
     * The three claims side by side, and the one that wins.
     *
     * [disagree] is true only when two *present* claims differ: a project with
     * only a `declare_id!` is not in disagreement with the keypair it does not
     * have yet, and a Native project with no Anchor.toml never disagrees with
     * a table that does not exist.
     */
    data class Resolved(
        val id: String?,
        val source: Source,
        val keypairId: String?,
        val declaredId: String?,
        val anchorTomlId: String?,
    ) {
        val disagree: Boolean
            get() = listOfNotNull(keypairId, declaredId, anchorTomlId).distinct().size > 1
    }

    /**
     * The id [program] deploys under on [cluster], and what the other two
     * sources say. Blocking file reads; call it off the main thread.
     */
    fun resolve(projectRoot: String, program: ProgramTarget, cluster: Cluster): Resolved {
        val keypairId = Keypair.read(keypairFile(projectRoot, program))?.publicKey?.base58
        val declared = libRsFile(projectRoot, program)
            ?.let { runCatching { it.readText() }.getOrNull() }
            ?.let { declaredId(it) }
        val anchorToml = File(projectRoot, "Anchor.toml")
        val tomlId = if (anchorToml.isFile) {
            val text = runCatching { anchorToml.readText() }.getOrNull()
            text?.let {
                AnchorToml.programId(it, cluster.anchorName, program.moduleName)
                    ?: AnchorToml.programId(it, cluster.anchorName, program.crateName)
            }
        } else {
            null
        }
        val (id, source) = when {
            keypairId != null -> keypairId to Source.Keypair
            declared != null -> declared to Source.DeclareId
            tomlId != null -> tomlId to Source.AnchorToml
            else -> null to Source.None
        }
        return Resolved(id, source, keypairId, declared, tomlId)
    }

    /**
     * The address inside the first `declare_id!("…")` of a lib.rs, or null.
     *
     * A regex rather than a Rust parser: the macro takes one string literal
     * and nothing else, whitespace around the parentheses is the only
     * variation seen in the wild, and the address is validated as Base58 of
     * the right length so a commented-out placeholder like `declare_id!("...")`
     * is not mistaken for an id.
     */
    fun declaredId(libRsText: String): String? {
        val match = DECLARE_ID.find(libRsText) ?: return null
        val id = match.groupValues[1]
        return id.takeIf { Base58.isPubkey(it) }
    }

    /** `<root>/target/deploy/<module>-keypair.json` — where every build puts it. */
    fun keypairFile(projectRoot: String, program: ProgramTarget): File =
        File(projectRoot, "target/deploy/${program.moduleName}-keypair.json")

    /**
     * The program keypair, generated and written if there is none yet.
     * Blocking; call it off the main thread.
     *
     * Generating here rather than failing is what lets a cloned project — or
     * a Native build through platform-tools' cargo, which writes no keypair —
     * deploy at all. The id it gets is fresh, which is exactly the case
     * [Resolved.disagree] exists to point out.
     */
    fun ensureKeypair(projectRoot: String, program: ProgramTarget): Keypair {
        val file = keypairFile(projectRoot, program)
        Keypair.read(file)?.let { return it }
        val fresh = Keypair.generate()
        Keypair.write(file, fresh)
        return fresh
    }

    /**
     * Whether any program in [layout] has two present sources that disagree —
     * the shape `BuildRunner.idsDisagree` wants. Anchor and Seahorse only:
     * a Native project has no `anchor keys sync` to promise, so a mismatch
     * there is not a thing the build could have fixed.
     *
     * The cluster is the one Anchor.toml names, falling back to
     * [Cluster.DEFAULT]; there is no Context here to ask [ClusterStore].
     */
    fun disagree(layout: ProjectLayout): Boolean {
        when (layout.framework) {
            ProjectFramework.Anchor, ProjectFramework.Seahorse -> Unit
            ProjectFramework.Native, ProjectFramework.Unknown -> return false
        }
        val anchorToml = File(layout.root, "Anchor.toml")
        val cluster = runCatching { anchorToml.readText() }.getOrNull()
            ?.let { AnchorToml.providerCluster(it) }
            ?.let { Cluster.fromAnchor(it) }
            ?: Cluster.DEFAULT
        return layout.programs.any { resolve(layout.root, it, cluster).disagree }
    }

    /**
     * The `lib.rs` that would carry [program]'s `declare_id!`, or null.
     *
     * Anchor keeps each program under `programs/<dir>/src/lib.rs`, and `<dir>`
     * is *usually* the crate name — but it is the directory's Cargo.toml that
     * decides, so a workspace whose folder is named differently is found by
     * reading those. Native is `src/lib.rs` at the root.
     */
    fun libRsFile(projectRoot: String, program: ProgramTarget): File? {
        val root = File(projectRoot)
        val programs = File(root, "programs")
        if (programs.isDirectory) {
            for (name in listOf(program.crateName, program.moduleName)) {
                val direct = File(programs, "$name/src/lib.rs")
                if (direct.isFile) return direct
            }
            for (dir in programs.listFiles().orEmpty()) {
                if (!dir.isDirectory) continue
                val manifest = File(dir, "Cargo.toml")
                if (!manifest.isFile) continue
                val parsed = runCatching { BuildTasks.parseManifest(manifest.readText()) }.getOrNull()
                    ?: continue
                if (parsed.packageName == program.crateName) {
                    val lib = File(dir, "src/lib.rs")
                    if (lib.isFile) return lib
                }
            }
        }
        val native = File(root, "src/lib.rs")
        return native.takeIf { it.isFile }
    }

    private val DECLARE_ID = Regex("""declare_id!\s*\(\s*"([1-9A-HJ-NP-Za-km-z]{32,44})"\s*\)""")
}
