package to.eyed.thragg.core

import java.io.File
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * What `tools/conformance-agent.py --spettro` emits, folded by the real fold.
 *
 * The gap this closes is the one that made the whole conformance agent worth
 * extending: the workflow card, the phase spine and the swarm's ghost cells
 * had unit tests over *hand-written* fixtures, and a hand-written fixture
 * proves only that the person who wrote the fold and the person who wrote the
 * fixture agreed. Here the fixture is generated by the same file the phone
 * talks to — `--dump <scenario>` prints exactly the messages it would send —
 * so a scenario that drifts from what the client classifies on fails here
 * rather than on a device three days later.
 *
 * The little applier below is the engine's `apply_tool_fields` and nothing
 * more: first non-null `rawInput` is kept for ever (W-09), later ones
 * overwrite `rawInput` alone, `content` replaces rather than appends, and the
 * result is handed to the production [AgentConversation.apply] so the parser
 * is on the path too.
 *
 * Skipped, loudly, where there is no python3 — the same bargain
 * `a_python_conformance_agent_survives_the_whole_flow` makes in the engine.
 */
class ConformanceScenarioTest {

    // --- running the agent ---------------------------------------------------

    private fun repoRoot(): File? {
        var here: File? = File(System.getProperty("user.dir") ?: ".").absoluteFile
        while (here != null) {
            if (File(here, "tools/conformance-agent.py").isFile) return here
            here = here.parentFile
        }
        return null
    }

    /**
     * A scenario's messages, in order. `_hold` markers are kept: they are how
     * a mid-run frame is addressed, and a run has frames its ending does not
     * describe.
     */
    private fun dump(scenario: String): List<JSONObject>? {
        val root = repoRoot() ?: return null
        val process = runCatching {
            ProcessBuilder(
                "python3",
                File(root, "tools/conformance-agent.py").absolutePath,
                "--dump",
                scenario,
            ).redirectErrorStream(false).start()
        }.getOrNull() ?: run {
            println("skipping: no python3 on this host")
            return null
        }
        val lines = process.inputStream.bufferedReader().readLines()
        process.waitFor()
        if (process.exitValue() != 0) return null
        return lines.filter { it.isNotBlank() }.map { JSONObject(it) }
    }

    /** Everything up to and including the named hold, or all of it. */
    private fun upToHold(messages: List<JSONObject>, label: String): List<JSONObject> {
        val at = messages.indexOfFirst { it.optString("_hold") == label }
        return if (at < 0) messages else messages.subList(0, at)
    }

    // --- the engine's half, in miniature -------------------------------------

    private class Draft(val id: String) {
        var title = ""
        var kind = "other"
        var status = "pending"
        var rawInput: JSONObject? = null
        var rawInputOpen: JSONObject? = null
        var markdown: String? = null
    }

    /**
     * The wire, applied the way `acp_thread.rs` applies it, then re-emitted as
     * the engine's own entry JSON so the production parser reads it.
     */
    private fun entriesOf(messages: List<JSONObject>): List<AgentEntry> {
        val drafts = LinkedHashMap<String, Draft>()
        for (message in messages) {
            val update = message.optJSONObject("params")?.optJSONObject("update") ?: continue
            val kind = update.optString("sessionUpdate")
            if (kind != "tool_call" && kind != "tool_call_update") continue
            val id = update.optString("toolCallId").takeIf { it.isNotEmpty() } ?: continue
            val draft = drafts.getOrPut(id) { Draft(id) }
            if (update.has("title")) draft.title = update.optString("title")
            if (update.has("kind")) draft.kind = update.optString("kind")
            if (update.has("status")) draft.status = update.optString("status")
            update.optJSONObject("rawInput")?.let { raw ->
                // Set once and never again: this is the whole of W-09.
                if (draft.rawInputOpen == null) draft.rawInputOpen = raw
                draft.rawInput = raw
            }
            update.optJSONArray("content")?.let { content ->
                draft.markdown = content.optJSONObject(0)
                    ?.optJSONObject("content")?.optString("text")
            }
        }
        val entries = JSONArray()
        drafts.values.forEachIndexed { index, draft ->
            val row = JSONObject()
                .put("index", index)
                .put("rev", 1)
                .put("kind", "tool_call")
                .put("id", draft.id)
                .put("turn", 1)
                .put("title", draft.title)
                .put("tool_kind", draft.kind)
                .put("status", draft.status)
            draft.rawInput?.let { row.put("rawInput", it.toString(2)) }
            draft.rawInputOpen?.let { row.put("rawInputOpen", it.toString(2)) }
            draft.markdown?.let {
                row.put(
                    "content",
                    JSONArray().put(JSONObject().put("type", "markdown").put("markdown", it)),
                )
            }
            entries.put(row)
        }
        val body = JSONObject()
            .put("revision", 1)
            .put("total", entries.length())
            .put("entries", entries)
        return AgentConversation().apply(body.toString()).entries
    }

    private fun runsOf(messages: List<JSONObject>): List<OrchRun> =
        foldOrchestration(entriesOf(messages))
            .filterIsInstance<TranscriptRow.Run>()
            .map { it.run }

    // --- the workflow --------------------------------------------------------

    @Test
    fun theWorkflowScenarioFoldsIntoOneRunWithItsDeclaredPhases() {
        val messages = dump("workflow") ?: return
        val rows = foldOrchestration(entriesOf(messages))
        val runs = rows.filterIsInstance<TranscriptRow.Run>()
        // ONE card. The two progress calls (`kind` phase and log) ride the
        // same tool name and must be absorbed, not drawn — a row per phase
        // transition buries the run it belongs to.
        assertEquals(1, runs.size)
        assertTrue(rows.none { it is TranscriptRow.Item })
        val run = runs.single().run as OrchRun.Workflow

        // Everything the finish update overwrote survives in the opening args.
        assertEquals("run-7", run.runId)
        assertEquals("review-changes", run.name)
        assertEquals("Review the diff, then refute each finding", run.description)
        assertEquals("saved", run.origin)
        assertEquals(listOf("Review", "Verify", "Report"), run.phases.map { it.title })
        assertEquals("one agent per dimension", run.phases[0].detail)
        assertTrue(run.phases.all { it.declared })

        // Seven agents, two failures, one replayed — and the two failures
        // arrived by different routes.
        assertEquals(7, run.counts.total)
        assertEquals(2, run.counts.failed)
        assertEquals(1, run.counts.cached)
        assertEquals(OrchStatus.Done, run.status)

        val review = run.phases[0]
        assertEquals(OrchCounts(3, 0, 2, 1, 0), review.counts)
        val failed = review.members.first { it.status == OrchStatus.Failed }
        assertEquals("review#3", failed.instance)
        assertEquals("exit 1: 2 tests failed in acp/bridge_test.go", failed.failureReason)

        // The call completed; the member did not. A client that reads only the
        // call status draws this one green.
        val verify = run.phases[1]
        val reported = verify.members.first { it.instance == "verify#3" }
        assertEquals(OrchStatus.Failed, reported.status)
        assertEquals("could not refute: the test is genuinely broken", reported.failureReason)
        assertTrue(verify.members.first { it.instance == "verify#2" }.cached)

        // `log()` lines exist in no structured channel at all; they are mined
        // out of the rendered tree, and this is the assertion that the tree
        // the agent writes is one the miner can read.
        assertEquals(4, run.logs.size)
        assertEquals("journal replayed 1 entry", run.logs.first())
        assertEquals("7 agents · 2 failed · 1 replayed", run.summary)
    }

    @Test
    fun theWorkflowIsWholeAtItsFirstFrameAndAtItsMiddleOne() {
        val messages = dump("workflow") ?: return

        // t=0: the run has declared three phases and nothing has landed. The
        // whole plan is visible before any work is — which is the argument for
        // declaring one at all.
        val opening = (runsOf(upToHold(messages, "workflow:t0")).single()) as OrchRun.Workflow
        assertEquals(3, opening.phases.size)
        assertTrue(opening.phases.all { it.isPending })
        assertEquals(OrchStatus.Running, opening.status)

        // Mid-run: one agent still moving beside one that failed, and the two
        // later phases still pending.
        val mid = (runsOf(upToHold(messages, "workflow:mid")).single()) as OrchRun.Workflow
        val review = mid.phases[0]
        assertEquals(OrchCounts(3, 1, 1, 1, 0), review.counts)
        assertEquals(OrchStatus.Running, review.status)
        // Running first, then failed, then done — never launch order once
        // something is wrong.
        assertEquals(
            listOf("review#2", "review#3", "review#1"),
            review.members.map { it.instance },
        )
        // A live member shows its LATEST child, not the task it was launched
        // with: in a fan-out the launch tasks are near-identical.
        assertEquals("read internal/acp/bridge.go", review.members.first().liveDetail)
        assertTrue(mid.phases[1].isPending && mid.phases[2].isPending)
    }

    // --- the swarm -----------------------------------------------------------

    @Test
    fun theSwarmPromisesItsDenominatorBeforeItLaunches() {
        val messages = dump("swarm") ?: return

        // Mid-ramp: eight launched of twenty, and the other twelve are ghosts
        // rather than a shrunken denominator. A meter that counted only what
        // had launched would read 8/8 and run backwards as the ramp continued.
        val ramping = runsOf(upToHold(messages, "swarm:ramp")).single() as OrchRun.Swarm
        assertEquals(20, ramping.items.size)
        assertEquals(8, ramping.members.size)
        assertEquals(12, ramping.pending.size)
        assertEquals(20, ramping.counts.total)
        assertEquals("code", ramping.subagentType)
        assertEquals("worktree", ramping.isolation)
        // The ninth item: eight members launched, so the ghosts start at index 8.
        assertEquals("internal/store/journal.go", ramping.pending.first())

        val settled = runsOf(messages).single() as OrchRun.Swarm
        assertEquals(20, settled.members.size)
        assertTrue(settled.pending.isEmpty())
        assertEquals(1, settled.counts.failed)
        // A provider's bare rate limit arrives as plain text, never as a
        // report — the case that matters most and the one that renders as an
        // empty red row when a client only looks for `summary`.
        val failed = settled.members.first { it.status == OrchStatus.Failed }
        assertEquals("code#4", failed.instance)
        assertEquals("429 after 3 attempts", failed.failureReason)
        // Failures lead once nothing is moving.
        assertEquals("code#4", settled.members.first().instance)
    }

    // --- the question form ---------------------------------------------------

    @Test
    fun theFormAsksFourQuestionsCoveringEveryControlTheSheetDraws() {
        val messages = dump("form") ?: return
        val ask = messages.first { it.optString("method") == "_spettro/question/ask" }
        val question = SpettroQuestion.parseAll(
            JSONArray().put(
                JSONObject()
                    .put("id", "question-1")
                    .put("payload", ask.getJSONObject("params")),
            ),
        ).single()

        assertEquals(4, question.version)
        assertEquals(4, question.questions.size)
        assertNotNull(question.context)

        val database = question.questions[0]
        assertEquals("Database", database.header)
        assertTrue(database.options.all { it.description != null })
        assertEquals("postgres", database.options.first { it.isRecommended }.id)
        assertTrue(!database.multiSelect)

        val migration = question.questions[1]
        assertTrue(migration.options.all { !it.preview.isNullOrBlank() })

        val checks = question.questions[2]
        assertTrue(checks.multiSelect)

        val free = question.questions[3]
        assertTrue(free.options.isEmpty())
        // No options at all is custom input by definition, whatever the flag
        // says — the alternative is a form with nothing to answer it with.
        assertTrue(free.allowCustomInput)

        // Nothing is preselected, including the recommendation: a question
        // left alone is OMITTED from the reply, which is not the same as
        // agreeing with the agent.
        val draft = QuestionDraft()
        assertEquals(null, database.answer(draft))
        val answered = database.answer(draft.toggle("mysql", multi = false))
        assertEquals(QuestionAnswer.Option("q-0", listOf("mysql"), null), answered)
    }

    // --- the gauge and the plan ---------------------------------------------

    @Test
    fun usageMovesSeveralTimesInOneTurnAndFallsOnce() {
        val messages = dump("usage") ?: return
        val samples = messages.mapNotNull { message ->
            val update = message.optJSONObject("params")?.optJSONObject("update")
            update?.takeIf { it.optString("sessionUpdate") == "usage_update" }
        }.map { update ->
            AgentUsage(
                used = update.optLong("used"),
                size = update.optLong("size"),
                tokensUsed = update.optJSONObject("_meta")
                    ?.optLong("spettro.app/tokensUsed"),
            )
        }
        assertTrue(samples.size >= 5)
        assertTrue(samples.none { it.size == 0L })
        // Occupancy is a gauge: it falls after a compaction, and a client that
        // drew it as a counter would show the window filling for ever.
        assertTrue(samples.zipWithNext().any { (a, b) -> b.used < a.used })
        assertTrue(samples.zipWithNext().all { (a, b) -> b.tokensUsed!! > a.tokensUsed!! })
        assertTrue(samples.any { it.isWarm })
        assertTrue(samples.any { it.isNearlyFull })
        assertEquals(0.9065f, samples.maxOf { it.fraction }, 0.001f)
    }

    @Test
    fun thePlanCarriesTheBlockedSuffixTheEngineLifts() {
        val messages = dump("blocked") ?: return
        val plans = messages.mapNotNull { message ->
            message.optJSONObject("params")?.optJSONObject("update")
                ?.takeIf { it.optString("sessionUpdate") == "plan" }
                ?.optJSONArray("entries")
        }
        assertTrue(plans.size >= 3)
        val blocked = plans.first().let { entries ->
            (0 until entries.length()).map { entries.getJSONObject(it).optString("content") }
        }
        // ACP has no blocked status, so the CLI says it in the text and the
        // engine lifts it (W-12). The agent must send the literal suffix or
        // there is nothing to lift.
        assertTrue(blocked.any { it.endsWith(" (blocked)") })
        val last = plans.last().let { entries ->
            (0 until entries.length()).map { entries.getJSONObject(it).optString("content") }
        }
        // …and must stop sending it when the dependency clears, or the task
        // stays blocked on screen for ever.
        assertTrue(last.none { it.endsWith(" (blocked)") })
    }
}
